### ISSUE TITLE
No Recipes for Chiseled Bookshelf Variants

### ISSUE THREAD

**Issue by pommellie** [pnk2u/More-Chiseled-Bookshelf-Variants#3]
(I play with a whole host of the More Variant mods, hence why I am finding so many of these issues.)

Minecraft 1.21 on Fabric

The chiseled bookshelf variants do not have recipes, but the Spruce Chiseled Bookshelf is using the Vanilla recipe.

**Comment by pnk2u** [comment]
I'm glad you're enjoying these mods and reporting all the issues you find. This one however I cannot reproduce.
Or only partially. The only recipe that doesn't work (because I forgot implementing it) is the vanilla/oak chiseled bookshelf. The way you can obtain the oak chiseled bookshelf is by crafting any other variant of chiseled bookshelf and then putting that in the crafting table. I will however soon in an update add a specific crafting recipe for the oak chiseled bookshelf as it obviously should have one.
If you're unable to craft any other variants that are not the the Oak variant, please send me a screenshot of your crafting table with the items in it.
Thank you for your patience. (:

**Comment by pommellie** [comment]
Oh! I checked again and it seems it IS only the oak chiseled bookshelf that isn't working properly with a recipe. All the others are working just fine! I am so sorry for the confusion with this, and I appreciate you pointing this out to me. (I have only been using Oak stuff for this build and for some reason didn't check the others other than Spruce... which I see now was silly of me ;;^-^)

Everything is working perfectly fine, and YES! I am _greatly_ enjoying these mods and love the cohesion they bring to builds. It helps greatly with my OCD and wanting things to look similar. I appreciate all the work that you do, your patience with responding to these issues, and your attentiveness to the mods to make sure they are working well.

I hope you have a wonderful day! And, again, thank you for these mods and the work you do.

**Comment by pnk2u** [comment]
Thank you so much for these kind words. It fills me with much joy to read how much you enjoy these mods. I appreciate you telling me this a lot, just as I appreciate a lot that you go out of your way to tell me about these issues so I can fix them.
I had a wonderful day, thank you, I hope you do, too.

PS: The update (1.5.5) is out and adds the missing recipe for the Oak Chiseled Bookshelf.
